In [45]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 


In [46]:
dataset= pd.read_csv('../input/lt-vehicle-loan-default-prediction/train.csv')
dataset_test = pd.read_csv('../input/lt-vehicle-loan-default-prediction/test.csv')
dataset = dataset.drop(['Date.of.Birth','DisbursalDate','AVERAGE.ACCT.AGE','CREDIT.HISTORY.LENGTH','PERFORM_CNS.SCORE.DESCRIPTION'], axis = 1)
dataset_test = dataset_test.drop(['Date.of.Birth','DisbursalDate','AVERAGE.ACCT.AGE','CREDIT.HISTORY.LENGTH','PERFORM_CNS.SCORE.DESCRIPTION'], axis = 1)
dataset =dataset.dropna(axis = 0 , how = 'any')
dataset_test =dataset_test.dropna(axis = 0 , how = 'any')

In [47]:
dataset.shape

(225493, 36)

In [48]:
X= dataset.iloc[:,:35].values
X_test2=dataset_test.iloc[:,:].values
Y = dataset.iloc[:,-1].values

In [49]:
print(X)

[[420825 50578 58400 ... 0 0 0]
 [537409 47145 65550 ... 0 1 0]
 [417566 53278 61360 ... 0 0 0]
 ...
 [613658 33484 71212 ... 0 0 0]
 [548084 34259 73286 ... 0 0 0]
 [630213 75751 116009 ... 0 0 0]]


In [50]:
Y

array([0, 1, 0, ..., 0, 0, 0])

In [51]:
Y.shape

(225493,)

In [52]:
X.shape

(225493, 35)

In [53]:
print(X_test2)

[[655269 53478 63558 ... 0 0 0]
 [723482 55513 63163 ... 1 0 1]
 [758529 65282 84320 ... 0 0 0]
 ...
 [709352 55243 72509 ... 0 0 0]
 [699795 55243 72509 ... 1 1 0]
 [755244 40274 72509 ... 0 0 0]]


In [54]:
X_test2.shape

(108949, 35)

In [55]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encode', OneHotEncoder(),[8])],remainder = 'passthrough')
ct.fit(X)
X = ct.transform(X)


In [56]:
X.shape

(225493, 36)

In [57]:
ct.fit(X_test2)
X_test2 = ct.transform(X_test2)

In [58]:
X_test2.shape

(108949, 36)

In [59]:
from sklearn.model_selection import train_test_split
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size = 0.2 , random_state = 42)

In [60]:
print(X_train)

[[0.0 1.0 585355 ... 0 0 0]
 [0.0 1.0 649627 ... 0 0 0]
 [1.0 0.0 430327 ... 0 0 0]
 ...
 [1.0 0.0 543218 ... 0 0 0]
 [1.0 0.0 577907 ... 0 0 0]
 [0.0 1.0 625675 ... 0 0 0]]


In [61]:
X_train.shape


(180394, 36)

In [62]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, Y_train)


/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [71]:
Y_pred = classifier.predict(X_test)

print(Y_pred)


[0 0 0 ... 0 0 0]


In [64]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(Y_pred,Y_test)
print(cm)
accuracy_score(Y_pred , Y_test)

[[35177  9921]
 [    1     0]]


0.7799951218430564

In [65]:
from sklearn.neighbors import KNeighborsClassifier
classifier_tree = KNeighborsClassifier(n_neighbors = 5)
classifier_tree.fit(X_train , Y_train)

KNeighborsClassifier()

In [66]:
Y_pred_tree = classifier_tree.predict(X_test)
print(Y_pred_tree)

[0 0 1 ... 0 0 0]


In [67]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm_tree = confusion_matrix(Y_pred_tree,Y_test)
print(cm_tree)
accuracy_score(Y_pred_tree , Y_test)

[[32319  8758]
 [ 2859  1163]]


0.7424111399365839

In [68]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters   =5 , init = 'k-means++',random_state = 42)
kmeans.fit(X_train, Y_train)

KMeans(n_clusters=5, random_state=42)

In [69]:
Y_pred_kmeans = kmeans.predict(X_test)
print(Y_pred_kmeans)

[0 0 0 ... 0 0 0]


In [70]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm_kmeans = confusion_matrix(Y_pred_kmeans,Y_test)
print(cm_kmeans)
accuracy_score(Y_pred_kmeans , Y_test)

[[34094  9764     0     0     0]
 [    0     0     0     0     0]
 [   49     2     0     0     0]
 [ 1032   153     0     0     0]
 [    3     2     0     0     0]]


0.755981285616089

In [72]:

##for test set result or prediction new dataset 

In [73]:
Y_new = classifier.predict(X_test2)
print(Y_new)

[0 0 0 ... 0 0 0]


In [76]:
Y_new_tree =classifier_tree.predict(X_test2)
print(Y_new_tree)

[0 0 1 ... 0 0 0]


In [77]:
Y_new_kmeans = kmeans.predict(X_test)
print(Y_new_kmeans)

NameError: name 'classifier_kmeans' is not defined